// 目前仅session接口可以自动创建列，JDBC目前还不支持，即使可以创建空表，insert 数据仍是失败的。

connect root/root;
--0.清理数据：删除数据库 
drop database test_db;
<<NULL;

--1. 创建数据库
create database test_db;

--2. 指定数据库
use test_db;

--3. 创建仅包含 time 列的空表
create table auto_table();

--4. 查看表以及
show tables;

--5. 表结构信息(仅有1列为time的结构信息)
desc auto_table;

--6. 写入数据（自动创建其他列）
INSERT INTO auto_table(time,device_id,s_0,s_1) values(1, 'd1', 1.1,false);
<<SQLSTATE;

--7. 清理数据：删除数据库 
drop database test_db;
<<NULL;