// 数据库启动前，需要修改如下配置参数
// enable_seq_space_compaction=false
// enable_unseq_space_compaction=false
// enable_cross_space_compaction=false
// inner_compaction_candidate_file_num=2
// compaction_schedule_interval_in_ms=1000

connect root/TimechoDB@2021;
--清理环境
DROP DATABASE root.**;
<<NULL;

--1. 创建数据库和时间序列
CREATE DATABASE root.repro;
CREATE TIMESERIES root.repro.s1 WITH DATATYPE=INT64;

--2. 查看数据库和时间序列
SHOW DATABASES root.repro;
SHOW TIMESERIES root.repro.s1;

--3.执行操作 
--3.1 第一个 TsFile：旧数据
INSERT INTO root.repro(time, s1) VALUES (1, 1);
FLUSH;
SELECT s1 FROM root.repro; 
DELETE TIMESERIES root.repro.s1;
SHOW TIMESERIES root.repro.s1;
CREATE TIMESERIES root.repro.s1 WITH DATATYPE=INT64;
SHOW TIMESERIES root.repro.s1;

--3.2 第二个 TsFile：新数据
INSERT INTO root.repro(time, s1) VALUES (2, 2);
FLUSH;
-- 此时正确：只有 (2, 2)
SELECT s1 FROM root.repro;

--开启compaction
SET CONFIGURATION 'enable_seq_space_compaction'='true';

sleep 2000;
-- 在这里等待 inner compaction 完成，再查询，预期返回一行 (2, 2)
SELECT s1 FROM root.repro;


--清理环境
DROP DATABASE root.**;
<<NULL;
