//参考issue：https://jira.infra.timecho.com:8443/browse/TIMECHODB-1173
//SELECT INTO 的target目标序列包含反引号时会写入错误序列


--0. 清理环境
connect root/TimechoDB@2021;
drop database root.**;
<<NULL;

--1. 插入数据，自动创建元数据
insert into root.bw.baoshan.`TEST100001`.`00`.`温度`(time,value) values(1,1);

--2. 查看元数据
show timeseries root.bw.**;

--3. 执行select into 
select avg(value) into root.bw.baoshan.`TEST100001`.`00`.`温度_avg_1h`(value) from root.bw.baoshan.`TEST100001`.`00`.`温度`;

--清理环境
drop database root.**;
<<NULL;