//删除用户
connect root/TimechoDB@2021;

--0.清理环境
DROP USER user01;
<<NULL;
DROP USER user02;
<<NULL;

--1.创建用户
CREATE USER user01 'Pass@123456789';
CREATE USER user02 'PassWd_@1234';

--2.查看已创建的用户列表
LIST USER;


--3.删除用户
DROP USER user01;

--4. 再次执行删除操作
DROP USER user01;
<<SQLSTATE;

--5.删除管理员root以及不存在的用户
DROP USER root;
<<SQLSTATE;
DROP USER user03;
<<SQLSTATE;

--6.删除子句中丢失元素
DROP user02;
<<SQLSTATE;

--7.查看当前用户列表
LIST USER;


--8.清理环境
DROP USER user01;
<<NULL;
DROP USER user02;
<<NULL;
