connect root/root;
// 测试运维命令权限: root用户拥有所有权限

-- 无需授权
show version;
<<CHECKCODE;

-- 1. maintain
show cluster;
<<CHECKCODE;
show cluster details;
<<CHECKCODE;
show variables;
SHOW QUERY PROCESSLIST;
<<CHECKCODE;
kill all queries;

-- 2.仅root用户拥有的权限: root 用户
show regions;
show schema regions;
show data regions;
flush;
clear cache;
--【2024年2月5日，由于手动合并命令会导致性能问题，故移除掉】
--merge;
set system to readonly;
set system to running;
load configuration;
show confignodes;
show datanodes;

