connect root/root;
// 测试运维命令权限: root用户拥有所有权限

-- 1. maintain
show cluster;
<<CHECKCODE;
show cluster details;
<<CHECKCODE;
show variables;
SHOW QUERY PROCESSLIST;
<<CHECKCODE;
kill all queries;

-- 2.仅root用户拥有的权限: root 用户
show version;
<<CHECKCODE;
show regions;
show schema regions;
show data regions;
flush;
clear cache;
merge;
set system to readonly;
set system to running;
load configuration;
show confignodes;
show datanodes;

