connect root/TimechoDB@2021;
-- 语法正确性验证

drop function my_avg;<<NULL;
drop function my_error;<<NULL;
drop function MY。AVG;<<NULL;
drop function `MY.AVG`;<<NULL;
drop function `my-avg`;<<NULL;
drop function 我的均值函数;<<NULL;
drop function 我的均值函数abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789;<<NULL;
drop function ``;<<NULL;
drop function `1`;<<NULL;
drop function null;<<NULL;
drop function true;<<NULL;
drop timeseries root.sg.d0.s0;<<NULL;
drop database root.**;<<NULL;


-- 准备数据
create TIMESERIES root.sg.d0.s0 int32;
insert into root.sg.d0(time,s0) values (-100,-100),(-90,-90),(-50,-50),(-30,-30),(-10,-10),(0,0),(10,10),(20,20),(30,30),(50,50);

-- 名称正确
create function MY。AVG as "org.example.UDAFExample";
select MY。AVG(s0) from root.sg.d0;

create function `my.avg` as "org.example.UDAFExample";
select `MY.AVG`(s0) from root.sg.d0;
create function `MY.AVG` as "org.example.UDAFExample";
<<SQLSTATE;

create function `my-avg` as "org.example.UDAFExample";
select `my-avg`(s0) from root.sg.d0;

create function 我的均值函数 as "org.example.UDAFExample";
select 我的均值函数(s0) from root.sg.d0;

create function 我的均值函数abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789 as "org.example.UDAFExample";
select 我的均值函数abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789(s0) from root.sg.d0;

create function `` as "org.example.UDAFExample";
select ``(s0) from root.sg.d0;

create function `1` as "org.example.UDAFExample";
select `1`(s0) from root.sg.d0;

create function null as "org.example.UDAFExample";
select null(s0) from root.sg.d0;

create function true as "org.example.UDAFExample";
select true(s0) from root.sg.d0;

//show functions;


drop function MY。AVG;
drop function `MY.AVG`;
drop function `my-avg`;
drop function 我的均值函数;
drop function 我的均值函数abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789_abcdefghijklmnopqrstuvwxyz0123456789;
drop function ``;
drop function `1`;
drop function null;
drop function true;




-- 名称error
create function STRING_CONTAINS as "org.example.UDAFExample";
<<SQLSTATE;
create function sum as "org.example.UDAFExample";
<<SQLSTATE;
create function  as "org.example.UDAFExample";
<<SQLSTATE;
create function 1 as "org.example.UDAFExample";
<<SQLSTATE;
create function 'a' as "org.example.UDAFExample";
<<SQLSTATE;
create function /a as "org.example.UDAFExample";
<<SQLSTATE;


-- 类名error
create function error_classname_1 as "";
<<SQLSTATE;
create function error_classname_2 as null;
<<SQLSTATE;
create function error_classname_3 as "org.example.UDAFExample2";
<<SQLSTATE;

create function error_uri_1 as "org.example.UDAFExample" using uri "file:///data/nginx/udaf-upload-1.0-SNAPSHOT-nonExist.jar";
<<SQLSTATE;
create function error_uri_2 as "org.example.UDAFExample" using uri "http://127.0.0.1:8085/udaf-upload-1.0-SNAPSHOT-nonExist.jar";
<<SQLSTATE;
create function error_uri_3 as "org.example.UDAFExample" using uri "";
<<SQLSTATE;
create function error_uri_4 as "org.example.UDAFExample" using uri ;
<<SQLSTATE;
create function error_uri_5 as "org.example.UDAFExample" using uri "https://dlcdn.apache.org/iotdb/0.13.4/apache-iotdb-0.13.4-grafana-connector-bin.zip";
<<SQLSTATE;

-- 顺序
create function error_order_1 using uri "file:///data/nginx/udaf-example-1.0-SNAPSHOT" as "org.example.UDAFExample" ;
<<SQLSTATE;
-- 空jar
create function error_empty_jar as "org.example.empty.jar" using uri "file:///data/nginx/udaf-upload-1.0-SNAPSHOT-empty.jar";
<<SQLSTATE;


-- 未implements UDAF
create function UDAFUnImplements as "UDAFUnImplements";
<<SQLSTATE;




-- udaf 不存在
select my_error(s0) from root.sg.d2;
//<<SQLSTATE;

-- timeseries 不存在
create function MY_AVG as "org.example.UDAFExample";
select my_avg(s10) from root.sg.d2;
//<<SQLSTATE;


drop function my_avg;<<NULL;
drop timeseries root.sg.d0.s0;<<NULL;
drop database root.**;<<NULL;


