-- 连接数据库
connect root/TimechoDB@2021;
-- 清除数据库
drop database test;
<<NULL;


create database test;

// 返回当前连接的模型类别
SHOW CURRENT_SQL_DIALECT;

// 返回当前登录的用户名
SHOW CURRENT_USER;

// 返回当前连接的数据库名
SHOW CURRENT_DATABASE;

use test;

SHOW CURRENT_DATABASE;

// 返回当前集群的版本
SHOW VERSION;
<<CHECKCODE;

// 返回当前集群的一些关键参数
SHOW VARIABLES;
<<CHECKCODE;

// 返回当前集群的id
SHOW CLUSTER_ID;
<<CHECKCODE;

// 返回当前客户端直连的 DataNode 进程所在服务器的时间(前后时间会不一致故一定报错)
SHOW CURRENT_TIMESTAMP;
<<CHECKCODE;

drop database test;