connect root/root;
-- 清理数据
drop database test;
<<NULL;


-- 1.ALTER ERROR
-- 1.1. 创建数据库
create database ALTER;
<<SQLSTATE;
create database db.ALTER;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 1.2.指定使用的数据库
use test; 

-- 1.3.元数据
-- 1.3.1 表名
create table ALTER 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 1.3.2 标识符列
create table table_01 
(
	ALTER STRING TAG
);
<<SQLSTATE;
-- 1.3.3 属性列
create table table_02
(
    ALTER STRING ATTRIBUTE
);
<<SQLSTATE;
-- 1.3.4 物理量列
create table table_03 
(
	ALTER INT32 FIELD
);
<<SQLSTATE;

-- 1.3.5 show
show tables;

--- 1.4 删除数据库
drop database test;


-- 2.AND ERROR
-- 2.1. 创建数据库
create database AND;
<<SQLSTATE;
create database db.AND;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 2.2.指定使用的数据库
use test; 

-- 2.3.元数据
-- 2.3.1 表名
create table AND 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 2.3.2 标识符列
create table table_01 
(
	AND STRING TAG
);
<<SQLSTATE;
-- 2.3.3 属性列
create table table_02
(
    AND STRING ATTRIBUTE
);
<<SQLSTATE;
-- 2.3.4 物理量列
create table table_03 
(
	AND INT32 FIELD
);
<<SQLSTATE;

-- 2.3.5 show
show tables;

--- 2.4 删除数据库
drop database test;


-- 3.AS ERROR
-- 3.1. 创建数据库
create database AS;
<<SQLSTATE;
create database db.AS;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 3.2.指定使用的数据库
use test; 

-- 3.3.元数据
-- 3.3.1 表名
create table AS 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 3.3.2 标识符列
create table table_01 
(
	AS STRING TAG
);
<<SQLSTATE;
-- 3.3.3 属性列
create table table_02
(
    AS STRING ATTRIBUTE
);
<<SQLSTATE;
-- 3.3.4 物理量列
create table table_03 
(
	AS INT32 FIELD
);
<<SQLSTATE;

-- 3.3.5 show
show tables;

--- 3.4 删除数据库
drop database test;


-- 4.BETWEEN ERROR
-- 4.1. 创建数据库
create database BETWEEN;
<<SQLSTATE;
create database db.BETWEEN;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 4.2.指定使用的数据库
use test; 

-- 4.3.元数据
-- 4.3.1 表名
create table BETWEEN 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 4.3.2 标识符列
create table table_01 
(
	BETWEEN STRING TAG
);
<<SQLSTATE;
-- 4.3.3 属性列
create table table_02
(
    BETWEEN STRING ATTRIBUTE
);
<<SQLSTATE;
-- 4.3.4 物理量列
create table table_03 
(
	BETWEEN INT32 FIELD
);
<<SQLSTATE;

-- 4.3.5 show
show tables;

--- 4.4 删除数据库
drop database test;


-- 5.BY ERROR
-- 5.1. 创建数据库
create database BY;
<<SQLSTATE;
create database db.BY;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 5.2.指定使用的数据库
use test; 

-- 5.3.元数据
-- 5.3.1 表名
create table BY 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 5.3.2 标识符列
create table table_01 
(
	BY STRING TAG
);
<<SQLSTATE;
-- 5.3.3 属性列
create table table_02
(
    BY STRING ATTRIBUTE
);
<<SQLSTATE;
-- 5.3.4 物理量列
create table table_03 
(
	BY INT32 FIELD
);
<<SQLSTATE;

-- 5.3.5 show
show tables;

--- 5.4 删除数据库
drop database test;


-- 6.CASE ERROR
-- 6.1. 创建数据库
create database CASE;
<<SQLSTATE;
create database db.CASE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 6.2.指定使用的数据库
use test; 

-- 6.3.元数据
-- 6.3.1 表名
create table CASE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 6.3.2 标识符列
create table table_01 
(
	CASE STRING TAG
);
<<SQLSTATE;
-- 6.3.3 属性列
create table table_02
(
    CASE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 6.3.4 物理量列
create table table_03 
(
	CASE INT32 FIELD
);
<<SQLSTATE;

-- 6.3.5 show
show tables;

--- 6.4 删除数据库
drop database test;


-- 7.CAST ERROR
-- 7.1. 创建数据库
create database CAST;
<<SQLSTATE;
create database db.CAST;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 7.2.指定使用的数据库
use test; 

-- 7.3.元数据
-- 7.3.1 表名
create table CAST 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 7.3.2 标识符列
create table table_01 
(
	CAST STRING TAG
);
<<SQLSTATE;
-- 7.3.3 属性列
create table table_02
(
    CAST STRING ATTRIBUTE
);
<<SQLSTATE;
-- 7.3.4 物理量列
create table table_03 
(
	CAST INT32 FIELD
);
<<SQLSTATE;

-- 7.3.5 show
show tables;

--- 7.4 删除数据库
drop database test;


-- 8.CONSTRAINT ERROR
-- 8.1. 创建数据库
create database CONSTRAINT;
<<SQLSTATE;
create database db.CONSTRAINT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 8.2.指定使用的数据库
use test; 

-- 8.3.元数据
-- 8.3.1 表名
create table CONSTRAINT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 8.3.2 标识符列
create table table_01 
(
	CONSTRAINT STRING TAG
);
<<SQLSTATE;
-- 8.3.3 属性列
create table table_02
(
    CONSTRAINT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 8.3.4 物理量列
create table table_03 
(
	CONSTRAINT INT32 FIELD
);
<<SQLSTATE;

-- 8.3.5 show
show tables;

--- 8.4 删除数据库
drop database test;


-- 9.CREATE ERROR
-- 9.1. 创建数据库
create database CREATE;
<<SQLSTATE;
create database db.CREATE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 9.2.指定使用的数据库
use test; 

-- 9.3.元数据
-- 9.3.1 表名
create table CREATE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 9.3.2 标识符列
create table table_01 
(
	CREATE STRING TAG
);
<<SQLSTATE;
-- 9.3.3 属性列
create table table_02
(
    CREATE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 9.3.4 物理量列
create table table_03 
(
	CREATE INT32 FIELD
);
<<SQLSTATE;

-- 9.3.5 show
show tables;

--- 9.4 删除数据库
drop database test;


-- 10.CROSS ERROR
-- 10.1. 创建数据库
create database CROSS;
<<SQLSTATE;
create database db.CROSS;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 10.2.指定使用的数据库
use test; 

-- 10.3.元数据
-- 10.3.1 表名
create table CROSS 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 10.3.2 标识符列
create table table_01 
(
	CROSS STRING TAG
);
<<SQLSTATE;
-- 10.3.3 属性列
create table table_02
(
    CROSS STRING ATTRIBUTE
);
<<SQLSTATE;
-- 10.3.4 物理量列
create table table_03 
(
	CROSS INT32 FIELD
);
<<SQLSTATE;

-- 10.3.5 show
show tables;

--- 10.4 删除数据库
drop database test;


-- 11.CUBE ERROR
-- 11.1. 创建数据库
create database CUBE;
<<SQLSTATE;
create database db.CUBE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 11.2.指定使用的数据库
use test; 

-- 11.3.元数据
-- 11.3.1 表名
create table CUBE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 11.3.2 标识符列
create table table_01 
(
	CUBE STRING TAG
);
<<SQLSTATE;
-- 11.3.3 属性列
create table table_02
(
    CUBE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 11.3.4 物理量列
create table table_03 
(
	CUBE INT32 FIELD
);
<<SQLSTATE;

-- 11.3.5 show
show tables;

--- 11.4 删除数据库
drop database test;


-- 12.CURRENT_CATALOG ERROR
-- 12.1. 创建数据库
create database CURRENT_CATALOG;
<<SQLSTATE;
create database db.CURRENT_CATALOG;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 12.2.指定使用的数据库
use test; 

-- 12.3.元数据
-- 12.3.1 表名
create table CURRENT_CATALOG 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 12.3.2 标识符列
create table table_01 
(
	CURRENT_CATALOG STRING TAG
);
<<SQLSTATE;
-- 12.3.3 属性列
create table table_02
(
    CURRENT_CATALOG STRING ATTRIBUTE
);
<<SQLSTATE;
-- 12.3.4 物理量列
create table table_03 
(
	CURRENT_CATALOG INT32 FIELD
);
<<SQLSTATE;

-- 12.3.5 show
show tables;

--- 12.4 删除数据库
drop database test;


-- 13.CURRENT_DATE ERROR
-- 13.1. 创建数据库
create database CURRENT_DATE;
<<SQLSTATE;
create database db.CURRENT_DATE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 13.2.指定使用的数据库
use test; 

-- 13.3.元数据
-- 13.3.1 表名
create table CURRENT_DATE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 13.3.2 标识符列
create table table_01 
(
	CURRENT_DATE STRING TAG
);
<<SQLSTATE;
-- 13.3.3 属性列
create table table_02
(
    CURRENT_DATE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 13.3.4 物理量列
create table table_03 
(
	CURRENT_DATE INT32 FIELD
);
<<SQLSTATE;

-- 13.3.5 show
show tables;

--- 13.4 删除数据库
drop database test;


-- 14.CURRENT_PATH ERROR
-- 14.1. 创建数据库
create database CURRENT_PATH;
<<SQLSTATE;
create database db.CURRENT_PATH;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 14.2.指定使用的数据库
use test; 

-- 14.3.元数据
-- 14.3.1 表名
create table CURRENT_PATH 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 14.3.2 标识符列
create table table_01 
(
	CURRENT_PATH STRING TAG
);
<<SQLSTATE;
-- 14.3.3 属性列
create table table_02
(
    CURRENT_PATH STRING ATTRIBUTE
);
<<SQLSTATE;
-- 14.3.4 物理量列
create table table_03 
(
	CURRENT_PATH INT32 FIELD
);
<<SQLSTATE;

-- 14.3.5 show
show tables;

--- 14.4 删除数据库
drop database test;


-- 15.CURRENT_ROLE ERROR
-- 15.1. 创建数据库
create database CURRENT_ROLE;
<<SQLSTATE;
create database db.CURRENT_ROLE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 15.2.指定使用的数据库
use test; 

-- 15.3.元数据
-- 15.3.1 表名
create table CURRENT_ROLE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 15.3.2 标识符列
create table table_01 
(
	CURRENT_ROLE STRING TAG
);
<<SQLSTATE;
-- 15.3.3 属性列
create table table_02
(
    CURRENT_ROLE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 15.3.4 物理量列
create table table_03 
(
	CURRENT_ROLE INT32 FIELD
);
<<SQLSTATE;

-- 15.3.5 show
show tables;

--- 15.4 删除数据库
drop database test;


-- 16.CURRENT_SCHEMA ERROR
-- 16.1. 创建数据库
create database CURRENT_SCHEMA;
<<SQLSTATE;
create database db.CURRENT_SCHEMA;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 16.2.指定使用的数据库
use test; 

-- 16.3.元数据
-- 16.3.1 表名
create table CURRENT_SCHEMA 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 16.3.2 标识符列
create table table_01 
(
	CURRENT_SCHEMA STRING TAG
);
<<SQLSTATE;
-- 16.3.3 属性列
create table table_02
(
    CURRENT_SCHEMA STRING ATTRIBUTE
);
<<SQLSTATE;
-- 16.3.4 物理量列
create table table_03 
(
	CURRENT_SCHEMA INT32 FIELD
);
<<SQLSTATE;

-- 16.3.5 show
show tables;

--- 16.4 删除数据库
drop database test;


-- 17.CURRENT_TIME ERROR
-- 17.1. 创建数据库
create database CURRENT_TIME;
<<SQLSTATE;
create database db.CURRENT_TIME;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 17.2.指定使用的数据库
use test; 

-- 17.3.元数据
-- 17.3.1 表名
create table CURRENT_TIME 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 17.3.2 标识符列
create table table_01 
(
	CURRENT_TIME STRING TAG
);
<<SQLSTATE;
-- 17.3.3 属性列
create table table_02
(
    CURRENT_TIME STRING ATTRIBUTE
);
<<SQLSTATE;
-- 17.3.4 物理量列
create table table_03 
(
	CURRENT_TIME INT32 FIELD
);
<<SQLSTATE;

-- 17.3.5 show
show tables;

--- 17.4 删除数据库
drop database test;


-- 18.CURRENT_TIMESTAMP ERROR
-- 18.1. 创建数据库
create database CURRENT_TIMESTAMP;
<<SQLSTATE;
create database db.CURRENT_TIMESTAMP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 18.2.指定使用的数据库
use test; 

-- 18.3.元数据
-- 18.3.1 表名
create table CURRENT_TIMESTAMP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 18.3.2 标识符列
create table table_01 
(
	CURRENT_TIMESTAMP STRING TAG
);
<<SQLSTATE;
-- 18.3.3 属性列
create table table_02
(
    CURRENT_TIMESTAMP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 18.3.4 物理量列
create table table_03 
(
	CURRENT_TIMESTAMP INT32 FIELD
);
<<SQLSTATE;

-- 18.3.5 show
show tables;

--- 18.4 删除数据库
drop database test;


-- 19.CURRENT_USER ERROR
-- 19.1. 创建数据库
create database CURRENT_USER;
<<SQLSTATE;
create database db.CURRENT_USER;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 19.2.指定使用的数据库
use test; 

-- 19.3.元数据
-- 19.3.1 表名
create table CURRENT_USER 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 19.3.2 标识符列
create table table_01 
(
	CURRENT_USER STRING TAG
);
<<SQLSTATE;
-- 19.3.3 属性列
create table table_02
(
    CURRENT_USER STRING ATTRIBUTE
);
<<SQLSTATE;
-- 19.3.4 物理量列
create table table_03 
(
	CURRENT_USER INT32 FIELD
);
<<SQLSTATE;

-- 19.3.5 show
show tables;

--- 19.4 删除数据库
drop database test;


-- 20.DEALLOCATE ERROR
-- 20.1. 创建数据库
create database DEALLOCATE;
<<SQLSTATE;
create database db.DEALLOCATE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 20.2.指定使用的数据库
use test; 

-- 20.3.元数据
-- 20.3.1 表名
create table DEALLOCATE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 20.3.2 标识符列
create table table_01 
(
	DEALLOCATE STRING TAG
);
<<SQLSTATE;
-- 20.3.3 属性列
create table table_02
(
    DEALLOCATE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 20.3.4 物理量列
create table table_03 
(
	DEALLOCATE INT32 FIELD
);
<<SQLSTATE;

-- 20.3.5 show
show tables;

--- 20.4 删除数据库
drop database test;


-- 21.DELETE ERROR
-- 21.1. 创建数据库
create database DELETE;
<<SQLSTATE;
create database db.DELETE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 21.2.指定使用的数据库
use test; 

-- 21.3.元数据
-- 21.3.1 表名
create table DELETE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 21.3.2 标识符列
create table table_01 
(
	DELETE STRING TAG
);
<<SQLSTATE;
-- 21.3.3 属性列
create table table_02
(
    DELETE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 21.3.4 物理量列
create table table_03 
(
	DELETE INT32 FIELD
);
<<SQLSTATE;

-- 21.3.5 show
show tables;

--- 21.4 删除数据库
drop database test;


-- 22.DESCRIBE ERROR
-- 22.1. 创建数据库
create database DESCRIBE;
<<SQLSTATE;
create database db.DESCRIBE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 22.2.指定使用的数据库
use test; 

-- 22.3.元数据
-- 22.3.1 表名
create table DESCRIBE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 22.3.2 标识符列
create table table_01 
(
	DESCRIBE STRING TAG
);
<<SQLSTATE;
-- 22.3.3 属性列
create table table_02
(
    DESCRIBE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 22.3.4 物理量列
create table table_03 
(
	DESCRIBE INT32 FIELD
);
<<SQLSTATE;

-- 22.3.5 show
show tables;

--- 22.4 删除数据库
drop database test;


-- 23.DISTINCT ERROR
-- 23.1. 创建数据库
create database DISTINCT;
<<SQLSTATE;
create database db.DISTINCT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 23.2.指定使用的数据库
use test; 

-- 23.3.元数据
-- 23.3.1 表名
create table DISTINCT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 23.3.2 标识符列
create table table_01 
(
	DISTINCT STRING TAG
);
<<SQLSTATE;
-- 23.3.3 属性列
create table table_02
(
    DISTINCT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 23.3.4 物理量列
create table table_03 
(
	DISTINCT INT32 FIELD
);
<<SQLSTATE;

-- 23.3.5 show
show tables;

--- 23.4 删除数据库
drop database test;


-- 24.DROP ERROR
-- 24.1. 创建数据库
create database DROP;
<<SQLSTATE;
create database db.DROP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 24.2.指定使用的数据库
use test; 

-- 24.3.元数据
-- 24.3.1 表名
create table DROP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 24.3.2 标识符列
create table table_01 
(
	DROP STRING TAG
);
<<SQLSTATE;
-- 24.3.3 属性列
create table table_02
(
    DROP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 24.3.4 物理量列
create table table_03 
(
	DROP INT32 FIELD
);
<<SQLSTATE;

-- 24.3.5 show
show tables;

--- 24.4 删除数据库
drop database test;


-- 25.ELSE ERROR
-- 25.1. 创建数据库
create database ELSE;
<<SQLSTATE;
create database db.ELSE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 25.2.指定使用的数据库
use test; 

-- 25.3.元数据
-- 25.3.1 表名
create table ELSE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 25.3.2 标识符列
create table table_01 
(
	ELSE STRING TAG
);
<<SQLSTATE;
-- 25.3.3 属性列
create table table_02
(
    ELSE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 25.3.4 物理量列
create table table_03 
(
	ELSE INT32 FIELD
);
<<SQLSTATE;

-- 25.3.5 show
show tables;

--- 25.4 删除数据库
drop database test;


-- 26.END ERROR
-- 26.1. 创建数据库
create database END;
<<SQLSTATE;
create database db.END;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 26.2.指定使用的数据库
use test; 

-- 26.3.元数据
-- 26.3.1 表名
create table END 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 26.3.2 标识符列
create table table_01 
(
	END STRING TAG
);
<<SQLSTATE;
-- 26.3.3 属性列
create table table_02
(
    END STRING ATTRIBUTE
);
<<SQLSTATE;
-- 26.3.4 物理量列
create table table_03 
(
	END INT32 FIELD
);
<<SQLSTATE;

-- 26.3.5 show
show tables;

--- 26.4 删除数据库
drop database test;


-- 27.ESCAPE ERROR
-- 27.1. 创建数据库
create database ESCAPE;
<<SQLSTATE;
create database db.ESCAPE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 27.2.指定使用的数据库
use test; 

-- 27.3.元数据
-- 27.3.1 表名
create table ESCAPE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 27.3.2 标识符列
create table table_01 
(
	ESCAPE STRING TAG
);
<<SQLSTATE;
-- 27.3.3 属性列
create table table_02
(
    ESCAPE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 27.3.4 物理量列
create table table_03 
(
	ESCAPE INT32 FIELD
);
<<SQLSTATE;

-- 27.3.5 show
show tables;

--- 27.4 删除数据库
drop database test;


-- 28.EXCEPT ERROR
-- 28.1. 创建数据库
create database EXCEPT;
<<SQLSTATE;
create database db.EXCEPT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 28.2.指定使用的数据库
use test; 

-- 28.3.元数据
-- 28.3.1 表名
create table EXCEPT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 28.3.2 标识符列
create table table_01 
(
	EXCEPT STRING TAG
);
<<SQLSTATE;
-- 28.3.3 属性列
create table table_02
(
    EXCEPT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 28.3.4 物理量列
create table table_03 
(
	EXCEPT INT32 FIELD
);
<<SQLSTATE;

-- 28.3.5 show
show tables;

--- 28.4 删除数据库
drop database test;


-- 29.EXISTS ERROR
-- 29.1. 创建数据库
create database EXISTS;
<<SQLSTATE;
create database db.EXISTS;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 29.2.指定使用的数据库
use test; 

-- 29.3.元数据
-- 29.3.1 表名
create table EXISTS 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 29.3.2 标识符列
create table table_01 
(
	EXISTS STRING TAG
);
<<SQLSTATE;
-- 29.3.3 属性列
create table table_02
(
    EXISTS STRING ATTRIBUTE
);
<<SQLSTATE;
-- 29.3.4 物理量列
create table table_03 
(
	EXISTS INT32 FIELD
);
<<SQLSTATE;

-- 29.3.5 show
show tables;

--- 29.4 删除数据库
drop database test;


-- 30.EXTRACT ERROR
-- 30.1. 创建数据库
create database EXTRACT;
<<SQLSTATE;
create database db.EXTRACT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 30.2.指定使用的数据库
use test; 

-- 30.3.元数据
-- 30.3.1 表名
create table EXTRACT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 30.3.2 标识符列
create table table_01 
(
	EXTRACT STRING TAG
);
<<SQLSTATE;
-- 30.3.3 属性列
create table table_02
(
    EXTRACT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 30.3.4 物理量列
create table table_03 
(
	EXTRACT INT32 FIELD
);
<<SQLSTATE;

-- 30.3.5 show
show tables;

--- 30.4 删除数据库
drop database test;


-- 31.FALSE ERROR
-- 31.1. 创建数据库
create database FALSE;
<<SQLSTATE;
create database db.FALSE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 31.2.指定使用的数据库
use test; 

-- 31.3.元数据
-- 31.3.1 表名
create table FALSE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 31.3.2 标识符列
create table table_01 
(
	FALSE STRING TAG
);
<<SQLSTATE;
-- 31.3.3 属性列
create table table_02
(
    FALSE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 31.3.4 物理量列
create table table_03 
(
	FALSE INT32 FIELD
);
<<SQLSTATE;

-- 31.3.5 show
show tables;

--- 31.4 删除数据库
drop database test;


-- 32.FOR ERROR
-- 32.1. 创建数据库
create database FOR;
<<SQLSTATE;
create database db.FOR;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 32.2.指定使用的数据库
use test; 

-- 32.3.元数据
-- 32.3.1 表名
create table FOR 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 32.3.2 标识符列
create table table_01 
(
	FOR STRING TAG
);
<<SQLSTATE;
-- 32.3.3 属性列
create table table_02
(
    FOR STRING ATTRIBUTE
);
<<SQLSTATE;
-- 32.3.4 物理量列
create table table_03 
(
	FOR INT32 FIELD
);
<<SQLSTATE;

-- 32.3.5 show
show tables;

--- 32.4 删除数据库
drop database test;


-- 33.FROM ERROR
-- 33.1. 创建数据库
create database FROM;
<<SQLSTATE;
create database db.FROM;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 33.2.指定使用的数据库
use test; 

-- 33.3.元数据
-- 33.3.1 表名
create table FROM 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 33.3.2 标识符列
create table table_01 
(
	FROM STRING TAG
);
<<SQLSTATE;
-- 33.3.3 属性列
create table table_02
(
    FROM STRING ATTRIBUTE
);
<<SQLSTATE;
-- 33.3.4 物理量列
create table table_03 
(
	FROM INT32 FIELD
);
<<SQLSTATE;

-- 33.3.5 show
show tables;

--- 33.4 删除数据库
drop database test;


-- 34.FULL ERROR
-- 34.1. 创建数据库
create database FULL;
<<SQLSTATE;
create database db.FULL;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 34.2.指定使用的数据库
use test; 

-- 34.3.元数据
-- 34.3.1 表名
create table FULL 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 34.3.2 标识符列
create table table_01 
(
	FULL STRING TAG
);
<<SQLSTATE;
-- 34.3.3 属性列
create table table_02
(
    FULL STRING ATTRIBUTE
);
<<SQLSTATE;
-- 34.3.4 物理量列
create table table_03 
(
	FULL INT32 FIELD
);
<<SQLSTATE;

-- 34.3.5 show
show tables;

--- 34.4 删除数据库
drop database test;


-- 35.GROUP ERROR
-- 35.1. 创建数据库
create database GROUP;
<<SQLSTATE;
create database db.GROUP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 35.2.指定使用的数据库
use test; 

-- 35.3.元数据
-- 35.3.1 表名
create table GROUP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 35.3.2 标识符列
create table table_01 
(
	GROUP STRING TAG
);
<<SQLSTATE;
-- 35.3.3 属性列
create table table_02
(
    GROUP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 35.3.4 物理量列
create table table_03 
(
	GROUP INT32 FIELD
);
<<SQLSTATE;

-- 35.3.5 show
show tables;

--- 35.4 删除数据库
drop database test;


-- 36.GROUPING ERROR
-- 36.1. 创建数据库
create database GROUPING;
<<SQLSTATE;
create database db.GROUPING;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 36.2.指定使用的数据库
use test; 

-- 36.3.元数据
-- 36.3.1 表名
create table GROUPING 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 36.3.2 标识符列
create table table_01 
(
	GROUPING STRING TAG
);
<<SQLSTATE;
-- 36.3.3 属性列
create table table_02
(
    GROUPING STRING ATTRIBUTE
);
<<SQLSTATE;
-- 36.3.4 物理量列
create table table_03 
(
	GROUPING INT32 FIELD
);
<<SQLSTATE;

-- 36.3.5 show
show tables;

--- 36.4 删除数据库
drop database test;


-- 37.HAVING ERROR
-- 37.1. 创建数据库
create database HAVING;
<<SQLSTATE;
create database db.HAVING;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 37.2.指定使用的数据库
use test; 

-- 37.3.元数据
-- 37.3.1 表名
create table HAVING 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 37.3.2 标识符列
create table table_01 
(
	HAVING STRING TAG
);
<<SQLSTATE;
-- 37.3.3 属性列
create table table_02
(
    HAVING STRING ATTRIBUTE
);
<<SQLSTATE;
-- 37.3.4 物理量列
create table table_03 
(
	HAVING INT32 FIELD
);
<<SQLSTATE;

-- 37.3.5 show
show tables;

--- 37.4 删除数据库
drop database test;


-- 38.IN ERROR
-- 38.1. 创建数据库
create database IN;
<<SQLSTATE;
create database db.IN;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 38.2.指定使用的数据库
use test; 

-- 38.3.元数据
-- 38.3.1 表名
create table IN 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 38.3.2 标识符列
create table table_01 
(
	IN STRING TAG
);
<<SQLSTATE;
-- 38.3.3 属性列
create table table_02
(
    IN STRING ATTRIBUTE
);
<<SQLSTATE;
-- 38.3.4 物理量列
create table table_03 
(
	IN INT32 FIELD
);
<<SQLSTATE;

-- 38.3.5 show
show tables;

--- 38.4 删除数据库
drop database test;


-- 39.INNER ERROR
-- 39.1. 创建数据库
create database INNER;
<<SQLSTATE;
create database db.INNER;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 39.2.指定使用的数据库
use test; 

-- 39.3.元数据
-- 39.3.1 表名
create table INNER 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 39.3.2 标识符列
create table table_01 
(
	INNER STRING TAG
);
<<SQLSTATE;
-- 39.3.3 属性列
create table table_02
(
    INNER STRING ATTRIBUTE
);
<<SQLSTATE;
-- 39.3.4 物理量列
create table table_03 
(
	INNER INT32 FIELD
);
<<SQLSTATE;

-- 39.3.5 show
show tables;

--- 39.4 删除数据库
drop database test;


-- 40.INSERT ERROR
-- 40.1. 创建数据库
create database INSERT;
<<SQLSTATE;
create database db.INSERT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 40.2.指定使用的数据库
use test; 

-- 40.3.元数据
-- 40.3.1 表名
create table INSERT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 40.3.2 标识符列
create table table_01 
(
	INSERT STRING TAG
);
<<SQLSTATE;
-- 40.3.3 属性列
create table table_02
(
    INSERT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 40.3.4 物理量列
create table table_03 
(
	INSERT INT32 FIELD
);
<<SQLSTATE;

-- 40.3.5 show
show tables;

--- 40.4 删除数据库
drop database test;


-- 41.INTERSECT ERROR
-- 41.1. 创建数据库
create database INTERSECT;
<<SQLSTATE;
create database db.INTERSECT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 41.2.指定使用的数据库
use test; 

-- 41.3.元数据
-- 41.3.1 表名
create table INTERSECT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 41.3.2 标识符列
create table table_01 
(
	INTERSECT STRING TAG
);
<<SQLSTATE;
-- 41.3.3 属性列
create table table_02
(
    INTERSECT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 41.3.4 物理量列
create table table_03 
(
	INTERSECT INT32 FIELD
);
<<SQLSTATE;

-- 41.3.5 show
show tables;

--- 41.4 删除数据库
drop database test;


-- 42.INTO ERROR
-- 42.1. 创建数据库
create database INTO;
<<SQLSTATE;
create database db.INTO;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 42.2.指定使用的数据库
use test; 

-- 42.3.元数据
-- 42.3.1 表名
create table INTO 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 42.3.2 标识符列
create table table_01 
(
	INTO STRING TAG
);
<<SQLSTATE;
-- 42.3.3 属性列
create table table_02
(
    INTO STRING ATTRIBUTE
);
<<SQLSTATE;
-- 42.3.4 物理量列
create table table_03 
(
	INTO INT32 FIELD
);
<<SQLSTATE;

-- 42.3.5 show
show tables;

--- 42.4 删除数据库
drop database test;


-- 43.IS ERROR
-- 43.1. 创建数据库
create database IS;
<<SQLSTATE;
create database db.IS;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 43.2.指定使用的数据库
use test; 

-- 43.3.元数据
-- 43.3.1 表名
create table IS 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 43.3.2 标识符列
create table table_01 
(
	IS STRING TAG
);
<<SQLSTATE;
-- 43.3.3 属性列
create table table_02
(
    IS STRING ATTRIBUTE
);
<<SQLSTATE;
-- 43.3.4 物理量列
create table table_03 
(
	IS INT32 FIELD
);
<<SQLSTATE;

-- 43.3.5 show
show tables;

--- 43.4 删除数据库
drop database test;


-- 44.JOIN ERROR
-- 44.1. 创建数据库
create database JOIN;
<<SQLSTATE;
create database db.JOIN;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 44.2.指定使用的数据库
use test; 

-- 44.3.元数据
-- 44.3.1 表名
create table JOIN 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 44.3.2 标识符列
create table table_01 
(
	JOIN STRING TAG
);
<<SQLSTATE;
-- 44.3.3 属性列
create table table_02
(
    JOIN STRING ATTRIBUTE
);
<<SQLSTATE;
-- 44.3.4 物理量列
create table table_03 
(
	JOIN INT32 FIELD
);
<<SQLSTATE;

-- 44.3.5 show
show tables;

--- 44.4 删除数据库
drop database test;


-- 45.JSON_ARRAY ERROR
-- 45.1. 创建数据库
create database JSON_ARRAY;
<<SQLSTATE;
create database db.JSON_ARRAY;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 45.2.指定使用的数据库
use test; 

-- 45.3.元数据
-- 45.3.1 表名
create table JSON_ARRAY 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 45.3.2 标识符列
create table table_01 
(
	JSON_ARRAY STRING TAG
);
<<SQLSTATE;
-- 45.3.3 属性列
create table table_02
(
    JSON_ARRAY STRING ATTRIBUTE
);
<<SQLSTATE;
-- 45.3.4 物理量列
create table table_03 
(
	JSON_ARRAY INT32 FIELD
);
<<SQLSTATE;

-- 45.3.5 show
show tables;

--- 45.4 删除数据库
drop database test;


-- 46.JSON_EXISTS ERROR
-- 46.1. 创建数据库
create database JSON_EXISTS;
<<SQLSTATE;
create database db.JSON_EXISTS;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 46.2.指定使用的数据库
use test; 

-- 46.3.元数据
-- 46.3.1 表名
create table JSON_EXISTS 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 46.3.2 标识符列
create table table_01 
(
	JSON_EXISTS STRING TAG
);
<<SQLSTATE;
-- 46.3.3 属性列
create table table_02
(
    JSON_EXISTS STRING ATTRIBUTE
);
<<SQLSTATE;
-- 46.3.4 物理量列
create table table_03 
(
	JSON_EXISTS INT32 FIELD
);
<<SQLSTATE;

-- 46.3.5 show
show tables;

--- 46.4 删除数据库
drop database test;


-- 47.JSON_OBJECT ERROR
-- 47.1. 创建数据库
create database JSON_OBJECT;
<<SQLSTATE;
create database db.JSON_OBJECT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 47.2.指定使用的数据库
use test; 

-- 47.3.元数据
-- 47.3.1 表名
create table JSON_OBJECT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 47.3.2 标识符列
create table table_01 
(
	JSON_OBJECT STRING TAG
);
<<SQLSTATE;
-- 47.3.3 属性列
create table table_02
(
    JSON_OBJECT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 47.3.4 物理量列
create table table_03 
(
	JSON_OBJECT INT32 FIELD
);
<<SQLSTATE;

-- 47.3.5 show
show tables;

--- 47.4 删除数据库
drop database test;


-- 48.JSON_QUERY ERROR
-- 48.1. 创建数据库
create database JSON_QUERY;
<<SQLSTATE;
create database db.JSON_QUERY;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 48.2.指定使用的数据库
use test; 

-- 48.3.元数据
-- 48.3.1 表名
create table JSON_QUERY 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 48.3.2 标识符列
create table table_01 
(
	JSON_QUERY STRING TAG
);
<<SQLSTATE;
-- 48.3.3 属性列
create table table_02
(
    JSON_QUERY STRING ATTRIBUTE
);
<<SQLSTATE;
-- 48.3.4 物理量列
create table table_03 
(
	JSON_QUERY INT32 FIELD
);
<<SQLSTATE;

-- 48.3.5 show
show tables;

--- 48.4 删除数据库
drop database test;


-- 49.JSON_TABLE ERROR
-- 49.1. 创建数据库
create database JSON_TABLE;
<<SQLSTATE;
create database db.JSON_TABLE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 49.2.指定使用的数据库
use test; 

-- 49.3.元数据
-- 49.3.1 表名
create table JSON_TABLE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 49.3.2 标识符列
create table table_01 
(
	JSON_TABLE STRING TAG
);
<<SQLSTATE;
-- 49.3.3 属性列
create table table_02
(
    JSON_TABLE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 49.3.4 物理量列
create table table_03 
(
	JSON_TABLE INT32 FIELD
);
<<SQLSTATE;

-- 49.3.5 show
show tables;

--- 49.4 删除数据库
drop database test;


-- 50.JSON_VALUE ERROR
-- 50.1. 创建数据库
create database JSON_VALUE;
<<SQLSTATE;
create database db.JSON_VALUE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 50.2.指定使用的数据库
use test; 

-- 50.3.元数据
-- 50.3.1 表名
create table JSON_VALUE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 50.3.2 标识符列
create table table_01 
(
	JSON_VALUE STRING TAG
);
<<SQLSTATE;
-- 50.3.3 属性列
create table table_02
(
    JSON_VALUE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 50.3.4 物理量列
create table table_03 
(
	JSON_VALUE INT32 FIELD
);
<<SQLSTATE;

-- 50.3.5 show
show tables;

--- 50.4 删除数据库
drop database test;


-- 51.LEFT ERROR
-- 51.1. 创建数据库
create database LEFT;
<<SQLSTATE;
create database db.LEFT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 51.2.指定使用的数据库
use test; 

-- 51.3.元数据
-- 51.3.1 表名
create table LEFT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 51.3.2 标识符列
create table table_01 
(
	LEFT STRING TAG
);
<<SQLSTATE;
-- 51.3.3 属性列
create table table_02
(
    LEFT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 51.3.4 物理量列
create table table_03 
(
	LEFT INT32 FIELD
);
<<SQLSTATE;

-- 51.3.5 show
show tables;

--- 51.4 删除数据库
drop database test;


-- 52.LIKE ERROR
-- 52.1. 创建数据库
create database LIKE;
<<SQLSTATE;
create database db.LIKE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 52.2.指定使用的数据库
use test; 

-- 52.3.元数据
-- 52.3.1 表名
create table LIKE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 52.3.2 标识符列
create table table_01 
(
	LIKE STRING TAG
);
<<SQLSTATE;
-- 52.3.3 属性列
create table table_02
(
    LIKE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 52.3.4 物理量列
create table table_03 
(
	LIKE INT32 FIELD
);
<<SQLSTATE;

-- 52.3.5 show
show tables;

--- 52.4 删除数据库
drop database test;


-- 53.LISTAGG ERROR
-- 53.1. 创建数据库
create database LISTAGG;
<<SQLSTATE;
create database db.LISTAGG;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 53.2.指定使用的数据库
use test; 

-- 53.3.元数据
-- 53.3.1 表名
create table LISTAGG 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 53.3.2 标识符列
create table table_01 
(
	LISTAGG STRING TAG
);
<<SQLSTATE;
-- 53.3.3 属性列
create table table_02
(
    LISTAGG STRING ATTRIBUTE
);
<<SQLSTATE;
-- 53.3.4 物理量列
create table table_03 
(
	LISTAGG INT32 FIELD
);
<<SQLSTATE;

-- 53.3.5 show
show tables;

--- 53.4 删除数据库
drop database test;


-- 54.LOCALTIME ERROR
-- 54.1. 创建数据库
create database LOCALTIME;
<<SQLSTATE;
create database db.LOCALTIME;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 54.2.指定使用的数据库
use test; 

-- 54.3.元数据
-- 54.3.1 表名
create table LOCALTIME 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 54.3.2 标识符列
create table table_01 
(
	LOCALTIME STRING TAG
);
<<SQLSTATE;
-- 54.3.3 属性列
create table table_02
(
    LOCALTIME STRING ATTRIBUTE
);
<<SQLSTATE;
-- 54.3.4 物理量列
create table table_03 
(
	LOCALTIME INT32 FIELD
);
<<SQLSTATE;

-- 54.3.5 show
show tables;

--- 54.4 删除数据库
drop database test;


-- 55.LOCALTIMESTAMP ERROR
-- 55.1. 创建数据库
create database LOCALTIMESTAMP;
<<SQLSTATE;
create database db.LOCALTIMESTAMP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 55.2.指定使用的数据库
use test; 

-- 55.3.元数据
-- 55.3.1 表名
create table LOCALTIMESTAMP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 55.3.2 标识符列
create table table_01 
(
	LOCALTIMESTAMP STRING TAG
);
<<SQLSTATE;
-- 55.3.3 属性列
create table table_02
(
    LOCALTIMESTAMP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 55.3.4 物理量列
create table table_03 
(
	LOCALTIMESTAMP INT32 FIELD
);
<<SQLSTATE;

-- 55.3.5 show
show tables;

--- 55.4 删除数据库
drop database test;


-- 56.NATURAL ERROR
-- 56.1. 创建数据库
create database NATURAL;
<<SQLSTATE;
create database db.NATURAL;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 56.2.指定使用的数据库
use test; 

-- 56.3.元数据
-- 56.3.1 表名
create table NATURAL 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 56.3.2 标识符列
create table table_01 
(
	NATURAL STRING TAG
);
<<SQLSTATE;
-- 56.3.3 属性列
create table table_02
(
    NATURAL STRING ATTRIBUTE
);
<<SQLSTATE;
-- 56.3.4 物理量列
create table table_03 
(
	NATURAL INT32 FIELD
);
<<SQLSTATE;

-- 56.3.5 show
show tables;

--- 56.4 删除数据库
drop database test;


-- 57.NORMALIZE ERROR
-- 57.1. 创建数据库
create database NORMALIZE;
<<SQLSTATE;
create database db.NORMALIZE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 57.2.指定使用的数据库
use test; 

-- 57.3.元数据
-- 57.3.1 表名
create table NORMALIZE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 57.3.2 标识符列
create table table_01 
(
	NORMALIZE STRING TAG
);
<<SQLSTATE;
-- 57.3.3 属性列
create table table_02
(
    NORMALIZE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 57.3.4 物理量列
create table table_03 
(
	NORMALIZE INT32 FIELD
);
<<SQLSTATE;

-- 57.3.5 show
show tables;

--- 57.4 删除数据库
drop database test;


-- 58.NOT ERROR
-- 58.1. 创建数据库
create database NOT;
<<SQLSTATE;
create database db.NOT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 58.2.指定使用的数据库
use test; 

-- 58.3.元数据
-- 58.3.1 表名
create table NOT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 58.3.2 标识符列
create table table_01 
(
	NOT STRING TAG
);
<<SQLSTATE;
-- 58.3.3 属性列
create table table_02
(
    NOT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 58.3.4 物理量列
create table table_03 
(
	NOT INT32 FIELD
);
<<SQLSTATE;

-- 58.3.5 show
show tables;

--- 58.4 删除数据库
drop database test;


-- 59.NULL ERROR
-- 59.1. 创建数据库
create database NULL;
<<SQLSTATE;
create database db.NULL;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 59.2.指定使用的数据库
use test; 

-- 59.3.元数据
-- 59.3.1 表名
create table NULL 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 59.3.2 标识符列
create table table_01 
(
	NULL STRING TAG
);
<<SQLSTATE;
-- 59.3.3 属性列
create table table_02
(
    NULL STRING ATTRIBUTE
);
<<SQLSTATE;
-- 59.3.4 物理量列
create table table_03 
(
	NULL INT32 FIELD
);
<<SQLSTATE;

-- 59.3.5 show
show tables;

--- 59.4 删除数据库
drop database test;


-- 60.ON ERROR
-- 60.1. 创建数据库
create database ON;
<<SQLSTATE;
create database db.ON;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 60.2.指定使用的数据库
use test; 

-- 60.3.元数据
-- 60.3.1 表名
create table ON 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 60.3.2 标识符列
create table table_01 
(
	ON STRING TAG
);
<<SQLSTATE;
-- 60.3.3 属性列
create table table_02
(
    ON STRING ATTRIBUTE
);
<<SQLSTATE;
-- 60.3.4 物理量列
create table table_03 
(
	ON INT32 FIELD
);
<<SQLSTATE;

-- 60.3.5 show
show tables;

--- 60.4 删除数据库
drop database test;


-- 61.OR ERROR
-- 61.1. 创建数据库
create database OR;
<<SQLSTATE;
create database db.OR;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 61.2.指定使用的数据库
use test; 

-- 61.3.元数据
-- 61.3.1 表名
create table OR 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 61.3.2 标识符列
create table table_01 
(
	OR STRING TAG
);
<<SQLSTATE;
-- 61.3.3 属性列
create table table_02
(
    OR STRING ATTRIBUTE
);
<<SQLSTATE;
-- 61.3.4 物理量列
create table table_03 
(
	OR INT32 FIELD
);
<<SQLSTATE;

-- 61.3.5 show
show tables;

--- 61.4 删除数据库
drop database test;


-- 62.ORDER ERROR
-- 62.1. 创建数据库
create database ORDER;
<<SQLSTATE;
create database db.ORDER;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 62.2.指定使用的数据库
use test; 

-- 62.3.元数据
-- 62.3.1 表名
create table ORDER 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 62.3.2 标识符列
create table table_01 
(
	ORDER STRING TAG
);
<<SQLSTATE;
-- 62.3.3 属性列
create table table_02
(
    ORDER STRING ATTRIBUTE
);
<<SQLSTATE;
-- 62.3.4 物理量列
create table table_03 
(
	ORDER INT32 FIELD
);
<<SQLSTATE;

-- 62.3.5 show
show tables;

--- 62.4 删除数据库
drop database test;


-- 63.OUTER ERROR
-- 63.1. 创建数据库
create database OUTER;
<<SQLSTATE;
create database db.OUTER;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 63.2.指定使用的数据库
use test; 

-- 63.3.元数据
-- 63.3.1 表名
create table OUTER 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 63.3.2 标识符列
create table table_01 
(
	OUTER STRING TAG
);
<<SQLSTATE;
-- 63.3.3 属性列
create table table_02
(
    OUTER STRING ATTRIBUTE
);
<<SQLSTATE;
-- 63.3.4 物理量列
create table table_03 
(
	OUTER INT32 FIELD
);
<<SQLSTATE;

-- 63.3.5 show
show tables;

--- 63.4 删除数据库
drop database test;


-- 64.PREPARE ERROR
-- 64.1. 创建数据库
create database PREPARE;
<<SQLSTATE;
create database db.PREPARE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 64.2.指定使用的数据库
use test; 

-- 64.3.元数据
-- 64.3.1 表名
create table PREPARE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 64.3.2 标识符列
create table table_01 
(
	PREPARE STRING TAG
);
<<SQLSTATE;
-- 64.3.3 属性列
create table table_02
(
    PREPARE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 64.3.4 物理量列
create table table_03 
(
	PREPARE INT32 FIELD
);
<<SQLSTATE;

-- 64.3.5 show
show tables;

--- 64.4 删除数据库
drop database test;


-- 65.RECURSIVE ERROR
-- 65.1. 创建数据库
create database RECURSIVE;
<<SQLSTATE;
create database db.RECURSIVE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 65.2.指定使用的数据库
use test; 

-- 65.3.元数据
-- 65.3.1 表名
create table RECURSIVE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 65.3.2 标识符列
create table table_01 
(
	RECURSIVE STRING TAG
);
<<SQLSTATE;
-- 65.3.3 属性列
create table table_02
(
    RECURSIVE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 65.3.4 物理量列
create table table_03 
(
	RECURSIVE INT32 FIELD
);
<<SQLSTATE;

-- 65.3.5 show
show tables;

--- 65.4 删除数据库
drop database test;


-- 66.RIGHT ERROR
-- 66.1. 创建数据库
create database RIGHT;
<<SQLSTATE;
create database db.RIGHT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 66.2.指定使用的数据库
use test; 

-- 66.3.元数据
-- 66.3.1 表名
create table RIGHT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 66.3.2 标识符列
create table table_01 
(
	RIGHT STRING TAG
);
<<SQLSTATE;
-- 66.3.3 属性列
create table table_02
(
    RIGHT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 66.3.4 物理量列
create table table_03 
(
	RIGHT INT32 FIELD
);
<<SQLSTATE;

-- 66.3.5 show
show tables;

--- 66.4 删除数据库
drop database test;


-- 67.ROLLUP ERROR
-- 67.1. 创建数据库
create database ROLLUP;
<<SQLSTATE;
create database db.ROLLUP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 67.2.指定使用的数据库
use test; 

-- 67.3.元数据
-- 67.3.1 表名
create table ROLLUP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 67.3.2 标识符列
create table table_01 
(
	ROLLUP STRING TAG
);
<<SQLSTATE;
-- 67.3.3 属性列
create table table_02
(
    ROLLUP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 67.3.4 物理量列
create table table_03 
(
	ROLLUP INT32 FIELD
);
<<SQLSTATE;

-- 67.3.5 show
show tables;

--- 67.4 删除数据库
drop database test;


-- 68.SELECT ERROR
-- 68.1. 创建数据库
create database SELECT;
<<SQLSTATE;
create database db.SELECT;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 68.2.指定使用的数据库
use test; 

-- 68.3.元数据
-- 68.3.1 表名
create table SELECT 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 68.3.2 标识符列
create table table_01 
(
	SELECT STRING TAG
);
<<SQLSTATE;
-- 68.3.3 属性列
create table table_02
(
    SELECT STRING ATTRIBUTE
);
<<SQLSTATE;
-- 68.3.4 物理量列
create table table_03 
(
	SELECT INT32 FIELD
);
<<SQLSTATE;

-- 68.3.5 show
show tables;

--- 68.4 删除数据库
drop database test;


-- 69.SKIP ERROR
-- 69.1. 创建数据库
create database SKIP;
<<SQLSTATE;
create database db.SKIP;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 69.2.指定使用的数据库
use test; 

-- 69.3.元数据
-- 69.3.1 表名
create table SKIP 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 69.3.2 标识符列
create table table_01 
(
	SKIP STRING TAG
);
<<SQLSTATE;
-- 69.3.3 属性列
create table table_02
(
    SKIP STRING ATTRIBUTE
);
<<SQLSTATE;
-- 69.3.4 物理量列
create table table_03 
(
	SKIP INT32 FIELD
);
<<SQLSTATE;

-- 69.3.5 show
show tables;

--- 69.4 删除数据库
drop database test;


-- 70.TABLE ERROR
-- 70.1. 创建数据库
create database TABLE;
<<SQLSTATE;
create database db.TABLE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 70.2.指定使用的数据库
use test; 

-- 70.3.元数据
-- 70.3.1 表名
create table TABLE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 70.3.2 标识符列
create table table_01 
(
	TABLE STRING TAG
);
<<SQLSTATE;
-- 70.3.3 属性列
create table table_02
(
    TABLE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 70.3.4 物理量列
create table table_03 
(
	TABLE INT32 FIELD
);
<<SQLSTATE;

-- 70.3.5 show
show tables;

--- 70.4 删除数据库
drop database test;


-- 71.THEN ERROR
-- 71.1. 创建数据库
create database THEN;
<<SQLSTATE;
create database db.THEN;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 71.2.指定使用的数据库
use test; 

-- 71.3.元数据
-- 71.3.1 表名
create table THEN 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 71.3.2 标识符列
create table table_01 
(
	THEN STRING TAG
);
<<SQLSTATE;
-- 71.3.3 属性列
create table table_02
(
    THEN STRING ATTRIBUTE
);
<<SQLSTATE;
-- 71.3.4 物理量列
create table table_03 
(
	THEN INT32 FIELD
);
<<SQLSTATE;

-- 71.3.5 show
show tables;

--- 71.4 删除数据库
drop database test;


-- 72.TRIM ERROR
-- 72.1. 创建数据库
create database TRIM;
<<SQLSTATE;
create database db.TRIM;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 72.2.指定使用的数据库
use test; 

-- 72.3.元数据
-- 72.3.1 表名
create table TRIM 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 72.3.2 标识符列
create table table_01 
(
	TRIM STRING TAG
);
<<SQLSTATE;
-- 72.3.3 属性列
create table table_02
(
    TRIM STRING ATTRIBUTE
);
<<SQLSTATE;
-- 72.3.4 物理量列
create table table_03 
(
	TRIM INT32 FIELD
);
<<SQLSTATE;

-- 72.3.5 show
show tables;

--- 72.4 删除数据库
drop database test;


-- 73.TRUE ERROR
-- 73.1. 创建数据库
create database TRUE;
<<SQLSTATE;
create database db.TRUE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 73.2.指定使用的数据库
use test; 

-- 73.3.元数据
-- 73.3.1 表名
create table TRUE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 73.3.2 标识符列
create table table_01 
(
	TRUE STRING TAG
);
<<SQLSTATE;
-- 73.3.3 属性列
create table table_02
(
    TRUE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 73.3.4 物理量列
create table table_03 
(
	TRUE INT32 FIELD
);
<<SQLSTATE;

-- 73.3.5 show
show tables;

--- 73.4 删除数据库
drop database test;


-- 74.UESCAPE ERROR
-- 74.1. 创建数据库
create database UESCAPE;
<<SQLSTATE;
create database db.UESCAPE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 74.2.指定使用的数据库
use test; 

-- 74.3.元数据
-- 74.3.1 表名
create table UESCAPE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 74.3.2 标识符列
create table table_01 
(
	UESCAPE STRING TAG
);
<<SQLSTATE;
-- 74.3.3 属性列
create table table_02
(
    UESCAPE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 74.3.4 物理量列
create table table_03 
(
	UESCAPE INT32 FIELD
);
<<SQLSTATE;

-- 74.3.5 show
show tables;

--- 74.4 删除数据库
drop database test;


-- 75.UNION ERROR
-- 75.1. 创建数据库
create database UNION;
<<SQLSTATE;
create database db.UNION;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 75.2.指定使用的数据库
use test; 

-- 75.3.元数据
-- 75.3.1 表名
create table UNION 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 75.3.2 标识符列
create table table_01 
(
	UNION STRING TAG
);
<<SQLSTATE;
-- 75.3.3 属性列
create table table_02
(
    UNION STRING ATTRIBUTE
);
<<SQLSTATE;
-- 75.3.4 物理量列
create table table_03 
(
	UNION INT32 FIELD
);
<<SQLSTATE;

-- 75.3.5 show
show tables;

--- 75.4 删除数据库
drop database test;


-- 76.UNNEST ERROR
-- 76.1. 创建数据库
create database UNNEST;
<<SQLSTATE;
create database db.UNNEST;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 76.2.指定使用的数据库
use test; 

-- 76.3.元数据
-- 76.3.1 表名
create table UNNEST 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 76.3.2 标识符列
create table table_01 
(
	UNNEST STRING TAG
);
<<SQLSTATE;
-- 76.3.3 属性列
create table table_02
(
    UNNEST STRING ATTRIBUTE
);
<<SQLSTATE;
-- 76.3.4 物理量列
create table table_03 
(
	UNNEST INT32 FIELD
);
<<SQLSTATE;

-- 76.3.5 show
show tables;

--- 76.4 删除数据库
drop database test;


-- 77.USING ERROR
-- 77.1. 创建数据库
create database USING;
<<SQLSTATE;
create database db.USING;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 77.2.指定使用的数据库
use test; 

-- 77.3.元数据
-- 77.3.1 表名
create table USING 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 77.3.2 标识符列
create table table_01 
(
	USING STRING TAG
);
<<SQLSTATE;
-- 77.3.3 属性列
create table table_02
(
    USING STRING ATTRIBUTE
);
<<SQLSTATE;
-- 77.3.4 物理量列
create table table_03 
(
	USING INT32 FIELD
);
<<SQLSTATE;

-- 77.3.5 show
show tables;

--- 77.4 删除数据库
drop database test;


-- 78.VALUES ERROR
-- 78.1. 创建数据库
create database VALUES;
<<SQLSTATE;
create database db.VALUES;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 78.2.指定使用的数据库
use test; 

-- 78.3.元数据
-- 78.3.1 表名
create table VALUES 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 78.3.2 标识符列
create table table_01 
(
	VALUES STRING TAG
);
<<SQLSTATE;
-- 78.3.3 属性列
create table table_02
(
    VALUES STRING ATTRIBUTE
);
<<SQLSTATE;
-- 78.3.4 物理量列
create table table_03 
(
	VALUES INT32 FIELD
);
<<SQLSTATE;

-- 78.3.5 show
show tables;

--- 78.4 删除数据库
drop database test;


-- 79.WHEN ERROR
-- 79.1. 创建数据库
create database WHEN;
<<SQLSTATE;
create database db.WHEN;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 79.2.指定使用的数据库
use test; 

-- 79.3.元数据
-- 79.3.1 表名
create table WHEN 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 79.3.2 标识符列
create table table_01 
(
	WHEN STRING TAG
);
<<SQLSTATE;
-- 79.3.3 属性列
create table table_02
(
    WHEN STRING ATTRIBUTE
);
<<SQLSTATE;
-- 79.3.4 物理量列
create table table_03 
(
	WHEN INT32 FIELD
);
<<SQLSTATE;

-- 79.3.5 show
show tables;

--- 79.4 删除数据库
drop database test;


-- 80.WHERE ERROR
-- 80.1. 创建数据库
create database WHERE;
<<SQLSTATE;
create database db.WHERE;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 80.2.指定使用的数据库
use test; 

-- 80.3.元数据
-- 80.3.1 表名
create table WHERE 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 80.3.2 标识符列
create table table_01 
(
	WHERE STRING TAG
);
<<SQLSTATE;
-- 80.3.3 属性列
create table table_02
(
    WHERE STRING ATTRIBUTE
);
<<SQLSTATE;
-- 80.3.4 物理量列
create table table_03 
(
	WHERE INT32 FIELD
);
<<SQLSTATE;

-- 80.3.5 show
show tables;

--- 80.4 删除数据库
drop database test;


-- 81.WITH ERROR
-- 81.1. 创建数据库
create database WITH;
<<SQLSTATE;
create database db.WITH;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 81.2.指定使用的数据库
use test; 

-- 81.3.元数据
-- 81.3.1 表名
create table WITH 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 81.3.2 标识符列
create table table_01 
(
	WITH STRING TAG
);
<<SQLSTATE;
-- 81.3.3 属性列
create table table_02
(
    WITH STRING ATTRIBUTE
);
<<SQLSTATE;
-- 81.3.4 物理量列
create table table_03 
(
	WITH INT32 FIELD
);
<<SQLSTATE;

-- 81.3.5 show
show tables;

--- 81.4 删除数据库
drop database test;


-- 82.FILL
-- 82.1. 创建数据库
create database FILL;
<<SQLSTATE;
create database db.FILL;
<<SQLSTATE;
create database test;
-- result:1
show databases;

-- 82.2.指定使用的数据库
use test; 

-- 82.3.元数据
-- 82.3.1 表名
create table FILL 
(
	device_id STRING TAG,
	s1 BOOLEAN FIELD,
	s2 INT32 FIELD
);
<<SQLSTATE;
-- 82.3.2 标识符列
create table table_01 
(
	FILL STRING TAG
);
<<SQLSTATE;
-- 82.3.3 属性列
create table table_02
(
    FILL STRING ATTRIBUTE
);
<<SQLSTATE;
-- 82.3.4 物理量列
create table table_03 
(
	FILL INT32 FIELD
);
<<SQLSTATE;

-- 82.3.5 show
show tables;

--- 82.4 删除数据库
drop database test;

