// 表模型：支持count database 语句

--0. 清理数据
connect root/TimechoDB@2021;
drop database test1;
<<NULL;
drop database test2;
<<NULL;

--1. 创建数据库
create database test1;
create database test2;

--2. 查看数据库
show databases;

--3. 统计数据库
count databases;

--4. 删除指定数据库后，再执行count databases
drop database test1;
show databases;
count databases;

--清理数据
connect root/TimechoDB@2021;
drop database test1;
<<NULL;
drop database test2;
<<NULL;
